// <auto-generated />
using System;
using AppBlazorEF.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppBlazorEF.Server.Migrations
{
    [DbContext(typeof(Facturacion_DBContext))]
    [Migration("20210220162038_proveedor")]
    partial class proveedor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

         
            modelBuilder.Entity("AppBlazorEF.Server.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .HasColumnName("ID_PROVEEDOR")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .HasColumnName("APELLIDO")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdProveedor");

                    b.ToTable("PROVEEDOR");
                });

#pragma warning restore 612, 618
        }
    }
}
